# Generated by Django 5.2 on 2025-05-09 17:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(default='')),
                ('output', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='NivelTeoria',
            fields=[
                ('nivel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='juegos.nivel')),
                ('contenido', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ap_paterno', models.CharField(max_length=50)),
                ('ap_materno', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('nivel_usuario', models.CharField(choices=[('Novato', 'Novato'), ('Junior', 'Junior'), ('Intermedio', 'Intermedio'), ('Semi Senior', 'Semi Senior'), ('Experto', 'Experto'), ('Senior', 'Senior')], default='Novato', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='usuarios/')),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='nivel',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='nivel',
            name='dificultad',
        ),
        migrations.RemoveField(
            model_name='nivel',
            name='nombre',
        ),
        migrations.AddField(
            model_name='nivel',
            name='nivel_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='juegos.nivel'),
        ),
        migrations.AddField(
            model_name='nivel',
            name='orden',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='nivel',
            name='puntos_recompensa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nivel',
            name='tipo',
            field=models.CharField(choices=[('Teoria', 'Teoria'), ('Ejercicio', 'Ejercicio'), ('Desafio', 'Desafio')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='nivel',
            name='titulo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(max_length=255)),
                ('orden', models.IntegerField(default=0)),
                ('capitulo_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='juegos.capitulo')),
            ],
        ),
        migrations.AddField(
            model_name='nivel',
            name='capitulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='juegos.capitulo'),
        ),
        migrations.CreateModel(
            name='NivelEjercicio',
            fields=[
                ('nivel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='juegos.nivel')),
                ('enunciado', models.TextField(default='')),
                ('solucion', models.TextField(default='')),
                ('casos_prueba', models.ManyToManyField(blank=True, to='juegos.casoprueba')),
            ],
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(default='')),
                ('imagen', models.CharField(max_length=255)),
                ('nivel_desbloqueo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='juegos.nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(default='')),
                ('imagen', models.CharField(max_length=255)),
                ('max_usos', models.IntegerField(default='')),
                ('personaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='juegos.personaje')),
            ],
        ),
        migrations.CreateModel(
            name='UsoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegos.capitulo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegos.item')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegos.nivel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegos.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_total', models.IntegerField(default=0)),
                ('capitulo_actual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='juegos.capitulo')),
                ('nivel_actual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='juegos.nivel')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='juegos.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='NivelCompletado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=True)),
                ('puntos_obtenidos', models.IntegerField(default=0)),
                ('intentos', models.IntegerField(default=1)),
                ('fecha_completado', models.DateTimeField(default=django.utils.timezone.now)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegos.nivel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegos.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'nivel')},
            },
        ),
        migrations.CreateModel(
            name='MochilaPersonaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegos.personaje')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegos.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='MochilaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegos.item')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegos.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Juego',
        ),
    ]
